hl.config({ { autogenerated = false } })
require("autostart")
require("monitor")
require("input")
require("looknfeel")
require("nvidia")

MainMod = "SUPER"
require("bindings.apps")
require("bindings.clipboard")
require("bindings.multimedia")
require("bindings.windows")
require("bindings.workspaces")
require("bindings.menus")
